# Generated by Django 4.1.4 on 2023-03-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('age', models.IntegerField()),
                ('House_number', models.CharField(max_length=100)),
                ('Residence', models.CharField(max_length=200)),
                ('Next_of_Kin', models.CharField(max_length=200)),
                ('Phone_number', models.CharField(max_length=200)),
                ('Occupation', models.CharField(max_length=200)),
                ('NHIS_number', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Folder_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
    ]
