# Generated by Django 4.1.4 on 2023-03-20 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrecord',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=datetime.datetime(2023, 3, 20, 12, 18, 4, 505757, tzinfo=datetime.timezone.utc), max_length=1),
            preserve_default=False,
        ),
    ]
