# Generated by Django 4.1.4 on 2023-03-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_doctor_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='NHIS',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
