# Generated by Django 4.1.4 on 2023-03-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_addrecord_gender'),
        ('members', '0002_laboratory_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antenatal_care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_examination', models.TextField()),
                ('drugs', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.addrecord')),
            ],
        ),
    ]
