# Generated by Django 4.1.4 on 2023-03-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='antenatal_care',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
