# Generated by Django 4.1.4 on 2023-03-20 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_addrecord_gender'),
        ('members', '0007_maternity_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='emergency_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_examination', models.TextField()),
                ('drugs', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.addrecord')),
            ],
        ),
    ]
